### ISSUE TITLE
v0.8.0 fails to build

### ISSUE THREAD

**Issue by jbeich** [phillbush/xnotify#6]
Regressed by 8c6a6f2a869a. From [error log](https://github.com/phillbush/xnotify/files/5620173/xnotify-0.8.0.log):
```c
xnotify.c:811:8: error: no member named 'sec' in 'struct Item'
        item->sec = itemspec->sec;
        ~~~~  ^
xnotify.c:811:24: error: no member named 'sec' in 'struct Itemspec'
        item->sec = itemspec->sec;
                    ~~~~~~~~  ^
xnotify.c:905:10: error: use of undeclared identifier 'SEC'
                return SEC;
                       ^
xnotify.c:931:12: error: no member named 'sec' in 'struct Itemspec'
        itemspec->sec = config.sec;
        ~~~~~~~~  ^
xnotify.c:958:8: error: use of undeclared identifier 'SEC'
                case SEC:
                     ^
xnotify.c:961:15: error: no member named 'sec' in 'struct Itemspec'
                                itemspec->sec = n;
                                ~~~~~~~~  ^
xnotify.c:1026:12: error: no member named 'sec' in 'struct Item'
                if (tmp->sec && time(NULL) - tmp->time > tmp->sec) {
                    ~~~  ^
xnotify.c:1026:49: error: no member named 'sec' in 'struct Item'
                if (tmp->sec && time(NULL) - tmp->time > tmp->sec) {
                                                         ~~~  ^
8 errors generated.
```

**Comment by phillbush** [comment]
damn, I forgot to `git add xnotify.h`.
Sorry about that!

**Comment by phillbush** [comment]
And that's [not even the first time](https://github.com/phillbush/xnotify/commit/bfc40030347c3c7bf94c3311a5123f116a14e5f2).  
I really should pay more attention before committing.
Thanks for the issue!
